<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\File;

class DocsController extends Controller
{
    /**
     * Display Swagger UI documentation
     */
    public function apiHtml()
    {
        return view('api-docs');
    }

    /**
     * Return JSON documentation (Swagger JSON) - Generated by l5-swagger
     */
    public function apiJson()
    {
        $jsonPath = storage_path('api-docs/api-docs.json');
        
        if (File::exists($jsonPath)) {
            return response()->json(json_decode(File::get($jsonPath), true));
        }
        
        // If not generated yet, redirect to generate it
        return redirect('/api/documentation');
    }
}


